services:
  proxy:
    image: httpd:2.4
    networks:
      - net
    volumes:
      - ./docker/development/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/development/ca.crt:/usr/local/apache2/conf/server.crt
      - ./docker/development/private.key:/usr/local/apache2/conf/server.key
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443

  backend:
    image: node:20
    networks:
      - net
    depends_on:
      - mysql
      - redis
    volumes:
      - ./logigator-backend/:/app
    working_dir: /app
    command: "sh -c 'corepack enable && yarn && exec yarn start'"
    environment:
      - DEBUG=express:*
      - DEBUG_COLORS=on

  editor:
    image: node:20
    networks:
      - net
    ports:
      - 9876:9876 # karma
    volumes:
      - ./logigator-editor-v2/:/app
    working_dir: /app
    command: "sh -c 'corepack enable && yarn && exec yarn start'"

  mysql:
    image: mysql:8
    networks:
      - net
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
    cap_add:
      - SYS_NICE
    command: --mysql-native-password=ON
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=logigator
      - MYSQL_USER=logigator
      - MYSQL_PASSWORD=logigator

  redis:
    image: redis:7
    networks:
      - net

  redis_ui:
    image: marian/rebrow:latest
    networks:
      - net
    ports:
      - 127.0.0.1:5001:5001

networks:
  net:
    driver: bridge
