services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./logigator-backend/config:/app/config

  mysql:
    image: mysql:8
    networks:
      - net
    ports:
      - "127.0.0.1:3306:3306"
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=logigator
      - MYSQL_USER=logigator
      - MYSQL_PASSWORD=logigator

  redis:
    image: redis:7
    networks:
      - net

  redis_ui:
    image: marian/rebrow:latest
    networks:
      - net
    ports:
      - "127.0.0.1:5001:5001"

networks:
  net:
    driver: bridge
