services:
  proxy:
    image: caddy:2-alpine
    networks:
      - net
    volumes:
      - ./Caddyfile.production:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:443:443'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net
    depends_on:
      - mysql
      - redis
    volumes:
      - ./logigator-backend/config:/app/config

  mysql:
    image: mysql:8.3
    networks:
      - net
    ports:
      - '127.0.0.1:3306:3306'
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=logigator
      - MYSQL_USER=logigator
      - MYSQL_PASSWORD=logigator

  redis:
    image: redis:8
    networks:
      - net

volumes:
  caddy_data:

networks:
  net:
    driver: bridge
