/**
 * Writes `logigator-web/src/app/pages/features/tour-media.ts` from what is on
 * disk under `logigator-web/src/assets/tour/`. The runner calls this once the
 * captures are written.
 *
 * The keys are composed from the file names this target writes — the
 * capability, then the language and the scheme — so the names are the authority
 * on what exists. The page's own rows name a capability and read the picture
 * through `webTourMedia`, which applies the fallback the documentation's
 * `docImages` does, across one more axis.
 */
import path from 'node:path';
import { LOCALES, THEMES } from '../../lib/config.mjs';
import {
  camelCase,
  captureFiles,
  importLines,
  writeGenerated
} from '../../lib/registry.mjs';
import { MEDIA_DIR, REGISTRY_FILE } from './config.mjs';

/** The name `fileName` composes, read back: capability, language, scheme. */
const FILE = new RegExp(`^(.+)-(${LOCALES.join('|')})-(${THEMES.join('|')})$`);

/**
 * Writes the import map for the tree at `dest` — the site's own root, so the
 * file lands at `<dest>/src/app/pages/features/tour-media.ts`.
 */
export function writeRegistry(dest) {
  const root = path.resolve(dest);
  const media = path.join(root, MEDIA_DIR);
  const registry = path.join(root, REGISTRY_FILE);

  const entries = captureFiles(media).map((file) => {
    const [, capability, lang, theme] = FILE.exec(path.parse(file).name) ?? [];
    return { file, capability, lang, theme };
  });
  const unmatched = entries.filter((entry) => !entry.capability);
  if (unmatched.length > 0) {
    throw new Error(
      `cannot tell a capability, language and scheme from ` +
        `${unmatched.map((entry) => entry.file).join(', ')} — the name is ` +
        '<capability>-<language>-<scheme>.webp'
    );
  }

  // `board-and-tools-en-light.webp` → `boardAndToolsEnLight`: the whole name,
  // which is already capability, language and scheme in one.
  const ident = (file) => camelCase(path.parse(file).name);

  const imports = importLines(
    entries.map((entry) => entry.file),
    registry,
    media,
    ident
  ).join('\n');
  const map = entries
    .map(
      ({ capability, lang, theme, file }) =>
        `  '${capability}:${lang}:${theme}': ${ident(file)}`
    )
    .join(',\n');

  const source = `${imports}

/**
 * Every captured tour figure, by \`<capability>:<language>:<scheme>\` — the
 * languages and schemes this target captured, without the English fallback
 * applied. Read it through {@link webTourMedia}.
 *
 * Generated by \`logigator-editor/tools/screenshots\` — capture a shot with
 * the \`web\` target and it appears here.
 */
const TOUR_MEDIA: Readonly<Record<string, string>> = {
${map}
};

/** One capability in one language and scheme, or \`undefined\` where there is none. */
function lookup(capability: string, lang: string, theme: string) {
  return TOUR_MEDIA[\`\${capability}:\${lang}:\${theme}\`];
}

/**
 * A figure's URL in one language and scheme, falling back the way the
 * documentation's images do: to English, and then to the first scheme
 * captured. A capability with no captures at all is \`undefined\` — a row that
 * has not been shot yet, rather than a broken picture.
 */
export function webTourMedia(
  language: string,
  colorScheme: string
): (capability: string) => string | undefined {
  return (capability) =>
    lookup(capability, language, colorScheme) ??
    lookup(capability, 'en', colorScheme) ??
    lookup(capability, 'en', ${JSON.stringify(THEMES[0])});
}
`;

  return writeGenerated(
    registry,
    source,
    entries.length > 0
      ? `${entries.length} figures`
      : 'no captures yet — every row reads as unshot'
  );
}
