name: 'CI logigator-editor'
on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'development'

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'never'
          cancel_others: 'true'
          skip_after_successful_duplicate: 'true'
          github_token: ${{ github.token }}
          paths: '["logigator-editor/**", "logigator-ui/**", "logigator-core/**", "logigator-contract/**", "logigator-docs/**", "package.json", "yarn.lock", ".yarnrc.yml", "angular.json", "tsconfig.json", "eslint.config.mjs"]'

  ci:
    name: 'CI logigator-editor'
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Setup Node'
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          package-manager-cache: false

      - name: Install Dependencies
        uses: ./.github/actions/yarn-install
        with:
          cache-prefix: workspace

      - name: 'Lint'
        shell: bash
        run: |
          yarn run lint:editor
          yarn run lint:ui
          yarn run lint:core
          yarn run lint:contract
          yarn run lint:docs

      - name: 'Typecheck'
        shell: bash
        run: |
          yarn run typecheck:core
          yarn run typecheck:contract
          yarn run typecheck:docs

      - name: 'Test'
        shell: bash
        run: |
          yarn run test:editor
          yarn run test:ui
          yarn run test:core
          yarn run test:contract
          yarn run test:docs

      - name: 'Build'
        shell: bash
        run: yarn run build:editor
